##############################
##########   Core   ##########
##############################
#
trustOperators: true
#
integrityShutdown: true
#
##############################
#########  Services  #########
##############################
#
services:
  dev: false
  entityManager: local